In [3]:
import numpy as np

# Day 5

## Part 1

In [4]:
def create_grid(data):#,idx_lines=0,idx_spread=1,idx_x_or_y=2):
    x_lim=np.max(data[:,:,0])+1#-np.min(data[:,:,0])#..................grid will be from 0 to maximum x value (0 and not minimum as the line values are the position on such a grid)
    y_lim=np.max(data[:,:,1])+1#-np.min(data[:,:,1])#..................grid will be from 0 to maximum x value
    return np.zeros((x_lim,y_lim))

def axial_lines(data):
    idx=np.logical_or((data[:,0,0]==data[:,1,0]),(data[:,0,1]==data[:,1,1]))
    #data_straight=data[idx,:,:]
    data_axial=np.hstack((np.sort(data[idx,:,0]),np.sort(data[idx,:,1])))
    return data_axial

def axial_vents_grid(data):
    threshold=2# count will be >= 2 when vent lines overlap
    grid=create_grid(data)
    str_lines=axial_lines(data)
    for line in str_lines:
        grid[line[0]:line[1]+1,line[2]:line[3]+1]+=1
    #print(np.transpose(grid_))
    vent_overlap=np.count_nonzero(grid >= threshold)
    return grid,vent_overlap

In [5]:
#d_=[['0,9', '5,9'],['8,0' ,'0,8'],['9,4' , '3,4'],['2,2' , '2,1'],['7,0' , '7,4'],['6,4', '2,0'],['0,9' ,'2,9'],['3,4' , '1,4'],['0,0' , '8,8'],['5,5' , '8,2']]
#data_=np.array(func(d_))#........shape->(10,2,2) with format (lines, initial and final, x and y)
#print(data_)


d=np.genfromtxt("DayFive_input.txt",delimiter='->',dtype='str')
func=lambda d: [[[int(y) for y in list(z.split(','))] for z in q] for q in d]
data=np.array(func(d))#........shape->(500,2,2) with format (lines, initial and final, x and y)

grid,vent_overlap=axial_vents_grid(data)
#print(np.transpose(grid))
print("Number of times horizontal and vertical vent lines overlap:",vent_overlap)

Number of times horizontal and vertical vent lines overlap: 7414


## Part 2

DO NOT sort the indices of diagonal lines. The order matters in that case.

In [144]:
def straight_lines_(data):
    axial_bool=np.logical_or((data[:,0,0]==data[:,1,0]),(data[:,0,1]==data[:,1,1]))
    daig_bool=(np.abs(data[:,0,0]-data[:,1,0])==np.abs(data[:,0,1]-data[:,1,1]))
    #idx_axis=np.any((horiz_bool,vert_bool,daig_bool),axis=0)#data_straight=data[idx,:,:]
    data_axis=np.hstack((np.sort(data[axial_bool,:,0]),np.sort(data[axial_bool,:,1]),(np.abs(data[axial_bool,0,0]-data[axial_bool,1,0])==np.abs(data[axial_bool,0,1]-data[axial_bool,1,1])).reshape(axial_bool.sum(),1)))
    data_diag=np.hstack((data[daig_bool,:,0],data[daig_bool,:,1],(np.abs(data[daig_bool,0,0]-data[daig_bool,1,0])==np.abs(data[daig_bool,0,1]-data[daig_bool,1,1])).reshape(daig_bool.sum(),1)))
    data_straight=np.vstack((data_axis,data_diag))
    return data_straight

def straight_vents_grid(data):
    threshold=2# count will be >= 2 when vent lines overlap
    grid=create_grid(data)
    str_lines=straight_lines_(data)
    for line in str_lines:
        if line[-1]==1:# condition for diagonal lines
            x=np.linspace(line[0],line[1],np.abs(line[0]-line[1])+1,dtype=int)
            y=np.linspace(line[2],line[3],np.abs(line[2]-line[3])+1,dtype=int)
            grid[x,y]+=1
        else:# axial lines
            grid[line[0]:line[1]+1,line[2]:line[3]+1]+=1
    #print(np.transpose(grid_))
    vent_overlap=np.count_nonzero(grid >= threshold)
    return grid,vent_overlap

In [145]:
grid,vent_overlap=straight_vents_grid(data)
#print(np.transpose(grid))
print("Number of times horizontal, vertical and diagonal vent lines overlap:",vent_overlap)

Number of times horizontal, vertical and diagonal vent lines overlap: 19676


###################################################################
## Another possible method?
Make a list of x axis numbers and y axis numbers that qualify as relevant lines and just count how many times each occur without even making a grid or anything!!!!

###################################################################


In [96]:
def straight_lines_(data):
    idx=np.logical_or((data[:,0,0]==data[:,1,0]),(data[:,0,1]==data[:,1,1]))
    #data_straight=data[idx,:,:]
    data_straight=np.hstack((np.sort(data[idx,:,0]),np.sort(data[idx,:,1]),(data[idx,0,0]==data[idx,1,0]).reshape(idx.sum(),1)))
    return data_straight

def straight_vents_grid(data):
    threshold=2# count will be >= 2 when vent lines overlap
    grid=create_grid(data)
    str_lines=straight_lines_(data)
    for line in str_lines:
        if line[-1]==1:
            grid[line[0],line[2]:line[3]+1]+=1
        else:
            grid[line[0]:line[1]+1,line[2]]+=1
    #print(np.transpose(grid_))
    vent_overlap=np.count_nonzero(grid >= threshold)
    return grid,vent_overlap

In [126]:
d_=[['0,9', '5,9'],['8,0' ,'0,8'],['9,4' , '3,4'],['2,2' , '2,1'],['7,0' , '7,4'],['6,4', '2,0'],['0,9' ,'2,9'],['3,4' , '1,4'],['0,0' , '8,8'],['5,5' , '8,2']]
data_=np.array(func(d_))#........shape->(10,2,2) with format (lines, initial and final, x and y)
#print(data_)

def create_grid(data):#,idx_lines=0,idx_spread=1,idx_x_or_y=2):
    x_lim=np.max(data[:,:,0])+1#-np.min(data[:,:,0])#..................grid will be from 0 to maximum x value (0 and not minimum as the line values are the position on such a grid)
    y_lim=np.max(data[:,:,1])+1#-np.min(data[:,:,1])#..................grid will be from 0 to maximum x value
    return np.zeros((x_lim,y_lim))

def straight_lines_(data):
    axial_bool=np.logical_or((data[:,0,0]==data[:,1,0]),(data[:,0,1]==data[:,1,1]))
    daig_bool=(np.abs(data[:,0,0]-data[:,1,0])==np.abs(data[:,0,1]-data[:,1,1]))
    #idx_axis=np.any((horiz_bool,vert_bool,daig_bool),axis=0)#data_straight=data[idx,:,:]
    data_axis=np.hstack((np.sort(data[axial_bool,:,0]),np.sort(data[axial_bool,:,1]),(np.abs(data[axial_bool,0,0]-data[axial_bool,1,0])==np.abs(data[axial_bool,0,1]-data[axial_bool,1,1])).reshape(axial_bool.sum(),1)))
    data_diag=np.hstack((data[daig_bool,:,0],data[daig_bool,:,1],(np.abs(data[daig_bool,0,0]-data[daig_bool,1,0])==np.abs(data[daig_bool,0,1]-data[daig_bool,1,1])).reshape(daig_bool.sum(),1)))
    data_straight=np.vstack((data_axis,data_diag))
    return data_straight

def straight_vents_grid(data):
    threshold=2# count will be >= 2 when vent lines overlap
    grid=create_grid(data)
    str_lines=straight_lines_(data)
    print(str_lines)
    for line in str_lines:
        if line[-1]==1:
            x=np.linspace(line[0],line[1],np.abs(line[0]-line[1])+1,dtype=int)
            y=np.linspace(line[2],line[3],np.abs(line[2]-line[3])+1,dtype=int)
            grid[x,y]+=1
        else:
            grid[line[0]:line[1]+1,line[2]:line[3]+1]+=1
    #print(np.transpose(grid_))
    vent_overlap=np.count_nonzero(grid >= threshold)
    return grid,vent_overlap


grid,vent_overlap=straight_vents_grid(data_)
print(np.transpose(grid))
print("Number of times horizontal, vertical and diagonal vent lines overlap:",vent_overlap)

[[0 5 9 9 0]
 [3 9 4 4 0]
 [2 2 1 2 0]
 [7 7 0 4 0]
 [0 2 9 9 0]
 [1 3 4 4 0]
 [8 0 0 8 1]
 [6 2 4 0 1]
 [0 8 0 8 1]
 [5 8 5 2 1]]
[[1. 0. 1. 0. 0. 0. 0. 1. 1. 0.]
 [0. 1. 1. 1. 0. 0. 0. 2. 0. 0.]
 [0. 0. 2. 0. 1. 0. 1. 1. 1. 0.]
 [0. 0. 0. 1. 0. 2. 0. 2. 0. 0.]
 [0. 1. 1. 2. 3. 1. 3. 2. 1. 1.]
 [0. 0. 0. 1. 0. 2. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [2. 2. 2. 1. 1. 1. 0. 0. 0. 0.]]
Number of times horizontal, vertical and diagonal vent lines overlap: 12
